# Applied Machine Learning (2022), exercises


## General instructions for all exercises

Follow the instructions and fill in your solution under the line marked by tag

> YOUR CODE HERE

Remove also line 

> raise NotImplementedError()

**Do not change other areas of the document**, since it may disturb the autograding of your results!
  
Having written the answer, execute the code cell by and pressing `Shift-Enter` key combination. The code is run, and it may print some information under the code cell. The focus automatically moves to the next cell and you may "execute" that cell by pressing `Shift-Enter` again, until you have reached the code cell which tests your solution. Execute that and follow the feedback. Usually it either says that the solution seems acceptable, or reports some errors. You can go back to your solution, modify it and repeat everything until you are satisfied. Then proceed to the next task.
   
Repeat the process for all tasks.

The notebook may also contain manually graded answers. Write your manually graded answer under the line marked by tag:

> YOUR ANSWER HERE

Manually graded tasks are text in markdown format. It may contain text, pseudocode, or mathematical formulas. You can write formulas with $\LaTeX$-syntax by enclosing the formula with dollar signs (`$`), for example `$f(x)=2 \pi / \alpha$`, will produce $f(x)=2 \pi / \alpha$

When you have passed the tests in the notebook, and you are ready to submit your solutions, download the whole notebook, using menu `File -> Download as -> Notebook (.ipynb)`. Save the file in your hard disk, and submit it in [Moodle](https://moodle.uwasa.fi) or EUNICE Moodle under the corresponding excercise.

Your solution should be an executable Python code. Use the code already existing as an example of Python programing and read more from the numerous Python programming material from the Internet if necessary. 


# Python warmup

## Create a  python data structures

1. Create an integer scalar variable `x`, and print it
1. Create a python list, `l`, and print it using function `list()` or directly with syntax `l=[1,4,2,3]`
1. Create a [numpy array](https://numpy.org/doc/stable/reference/generated/numpy.array.html), `a`, and print it. Tip: Import numpy library first by using: ```import numpy as np``` 

Python lists are suitable in many cases, but they are not efficient for large amounts of data or mathematical operations. Numpy arrays include a lot of useful functions which are packaged in numpy arrays.

In [ ]:
class Node:
    def __init__(self, name):
        self.name = name
        self.visited = False
        self.neighbors = []

def bfs(node):
    queue = []
    queue.append(node)
    node.visited = True

    while queue:
        current_node = queue.pop(0)
        print(current_node.name)

        for neighbor in current_node.neighbors:
            if not neighbor.visited:
                queue.append(neighbor)
                neighbor.visited = True

# Create the nodes in the graph
nodes = {
    "R": Node("R"),
    "K": Node("K"),
    "2": Node("2"),
    "3": Node("3"),
    "4": Node("4"),
    "5": Node("5"),
    "6": Node("6"),
}

# Connect the nodes with edges
nodes["R"].neighbors = [nodes["2"], nodes["K"]]
nodes["K"].neighbors = [nodes["3"], nodes["4"]]
nodes["2"].neighbors = [nodes["5"]]
nodes["3"].neighbors = [nodes["6"]]

# Start the BFS from node R
bfs(nodes["R"])

In [4]:
import numpy as np
x = 5
print(x)
l= (1,2,3,4,5)
print(list)
a = np.array((1,2,3,4), dtype=int)
print(a)

5
(1, 2, 3, 4, 5)
[1 2 3 4]


In [3]:
if 'x' not in globals():
    print("x not found! Please define x as scalar variable.")
elif 'l' not in globals():
    print("l not found! Please define l list.")
elif 'a' not in globals():
    print("a not found! Please define a as numpy array.")
else:
    print("No errors found this far. Your code may work.")


No errors found this far. Your code may work.


## Use numpy functions for creating arrays

1. Create a numpy array, `values`, which has 100 consequent values between 0 and $\pi$ using [np.linspace()](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html?highlight=linspace#numpy.linspace). Use ```np.pi``` as constant for $\pi$.
1. Create a two-dimensional array `M` of 5x5 [zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html?highlight=zeros#numpy.zeros) or 5x5 [ones](https://numpy.org/doc/stable/reference/generated/numpy.ones.html?highlight=ones#numpy.ones). using appropriate functions
1. Create one more 2 dimensional array with the following code ```A=np.array([[1,2,3], [4,5,6]])```

**TIP:** to find out what other functions or constants are included in NumPy package, write `np.` in the command line, and press TAB-key to get a list of possible completions, or SHIFT-TAB to get the help window.

In [11]:
# YOUR CODE HERE
values = np.linspace(0,np.pi)
print(values)
M = np.zeros((5,5))
print(M)
A = np.array([[1,2,3], [4,5,6]])
print(A)

[0.         0.06411414 0.12822827 0.19234241 0.25645654 0.32057068
 0.38468481 0.44879895 0.51291309 0.57702722 0.64114136 0.70525549
 0.76936963 0.83348377 0.8975979  0.96171204 1.02582617 1.08994031
 1.15405444 1.21816858 1.28228272 1.34639685 1.41051099 1.47462512
 1.53873926 1.60285339 1.66696753 1.73108167 1.7951958  1.85930994
 1.92342407 1.98753821 2.05165235 2.11576648 2.17988062 2.24399475
 2.30810889 2.37222302 2.43633716 2.5004513  2.56456543 2.62867957
 2.6927937  2.75690784 2.82102197 2.88513611 2.94925025 3.01336438
 3.07747852 3.14159265]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1 2 3]
 [4 5 6]]


In [13]:
errorfound=False
require=('values', 'M', 'A')
for var in require:
    if var not in globals():
        print(var, "not found! Please define it.")
        errorfound=True
if not errorfound:
    print("No errrors found")
        

No errrors found


## Manipulate data structures
1. Study the shape of previously created numpy arrays by using function ```.shape()``` included in the arrays you created.
1. Try to calculate also the sum of all values in those arrays with ```.sum()``` function. Store the sum of array `values` to variable called `s`.
1. Transpose a two dimensional array with function ```.T``` for example ```A.T``` and name the result as `tA`
1. Transposing a one dimensional array looks sadly slightly illogical, because it needs to be also converted to two dimensional at the same time. The row vector `values` can be transposed to column vector with syntax `
values.reshape(-1,1)`. Try it and name the result as `tvalues`. 
1. Try also to transpose the column vector back to row vector


In [14]:
values.shape

(50,)

In [15]:
M.shape

(5, 5)

In [16]:
A.shape

(2, 3)

In [17]:
s = values.sum()

In [20]:
tA = A.T

In [21]:
tA

array([[1, 4],
       [2, 5],
       [3, 6]])

In [22]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
tvalues = values.reshape(-1,1)

In [24]:
tvalues

array([[0.        ],
       [0.06411414],
       [0.12822827],
       [0.19234241],
       [0.25645654],
       [0.32057068],
       [0.38468481],
       [0.44879895],
       [0.51291309],
       [0.57702722],
       [0.64114136],
       [0.70525549],
       [0.76936963],
       [0.83348377],
       [0.8975979 ],
       [0.96171204],
       [1.02582617],
       [1.08994031],
       [1.15405444],
       [1.21816858],
       [1.28228272],
       [1.34639685],
       [1.41051099],
       [1.47462512],
       [1.53873926],
       [1.60285339],
       [1.66696753],
       [1.73108167],
       [1.7951958 ],
       [1.85930994],
       [1.92342407],
       [1.98753821],
       [2.05165235],
       [2.11576648],
       [2.17988062],
       [2.24399475],
       [2.30810889],
       [2.37222302],
       [2.43633716],
       [2.5004513 ],
       [2.56456543],
       [2.62867957],
       [2.6927937 ],
       [2.75690784],
       [2.82102197],
       [2.88513611],
       [2.94925025],
       [3.013

In [25]:


require=('s', 'tA', 'tvalues')
for var in require:
    if var not in globals():
        print(var, "not found! Please define it.")
        

# Language featuers

Answer shortly, with explanations to the following questions
1. Is Python an object oriented language?
1. Is Python interpreted or compiled language?
1. Is Python fast to run?

YOUR ANSWER HERE

## Summary
1. NumPy arrays are very important data structures in Python for machine learning and mathematical operations
1. Numpy arrays can be 1 dimensional or many dimensional
1. Two dimensional arrays can be transposed like matrices in mathematics 
1. Numpy arrays contain a large amount of functions which can be applied to their content